#include<stdio.h>
#include<conio.h>
#include<math.h>

void main()
{
    double a;

    printf("INPUT a = ");
    scanf("%lf", &a);
    printf("sin(%6.3lf) = %6.3lf\n", a, sin(a * M_PI / 180)); //sin(a)=...
    printf("arccos(%6.3lf) = %6.3lf\n", a, acos(a)); //arccos(a)==...
    printf("exp(%6.3lf) = %6.3lf\n", a, exp(a)); //ехр(a).==...
    printf("ln(%6.3lf) = %6.3lf\n",a , log(a)); //ln(a)=^...
    printf("ceil(%6.3lf) = %6.3lf\n",a , ceil(a)); //ceil(a)=...
    printf("floor(%6.3lf) = %6.3lf\n",a , floor(a)); //floor(a)=...
    printf("sqrt(%6.3lf = %6.3lf\n",a , sqrt(a)); //sqrt(a)=Е
    printf("pow(2,%6.3lf) = %6.3lf\n",a , pow(2,a)); //pow(2,a)=...

    return 0;
}
